In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Combined.csv")

C:\Users\haluk\AppData\Local\Temp\ipykernel_3384\1424832204.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Combined.csv")


## EDA

In [3]:
df.T

0       1            2            3            4        \
Unnamed: 0        0       1            2            3            4   
Seq               1       2            3            4            5   
Dur             0.0     0.0      4.99802     4.998037     4.999453   
RunTime         0.0     0.0      4.99802     4.998037     4.999453   
Mean            0.0     0.0      4.99802     4.998037     4.999453   
Sum             0.0     0.0      4.99802     4.998037     4.999453   
Min             0.0     0.0      4.99802     4.998037     4.999453   
Max             0.0     0.0      4.99802     4.998037     4.999453   
Proto          icmp    icmp          udp          udp          udp   
sTos            0.0     0.0          0.0          0.0          0.0   
dTos            NaN     NaN          0.0          0.0          0.0   
sDSb            cs0     cs0          cs0          cs0          cs0   
dDSb            NaN     NaN          cs0          cs0          cs0   
sTtl           58.0    58.0        117.0        117.0        117.0   
dTtl            NaN     NaN         64.0         64.0         64.0   
sHops           6.0     6.0         11.0         11.0         11.0   
dHops           NaN     NaN          0.0          0.0          0.0   
Cause         Start   Start        Start        Start        Start   
TotPkts           1       1          214          184          223   
SrcPkts           1       1          196          163          204   
DstPkts           0       0           18           21           19   
TotBytes         98      98       249093       221712       280216   
SrcBytes         98      98       244212       216245       275723   
DstBytes          0       0         4881         5467         4493   
Offset          128     232          336          440          544   
sMeanPktSz     98.0    98.0  1245.979614  1326.656494  1351.583374   
dMeanPktSz      0.0     0.0   271.166656   260.333344   236.473679   
Load            0.0     0.0   396280.125  352339.9375  445855.1563   
SrcLoad         0.0     0.0  388901.1875  344005.4688  439043.2188   
DstLoad         0.0     0.0  7378.921875  8334.472656  6811.945312   
Loss              0       0            0            0            0   
SrcLoss           0       0            0            0            0   
DstLoss           0       0            0            0            0   
pLoss           0.0     0.0          0.0          0.0          0.0   
SrcGap          NaN     NaN          NaN          NaN          NaN   
DstGap          NaN     NaN          NaN          NaN          NaN   
Rate            0.0     0.0    42.616875    36.614376    44.404858   
SrcRate         0.0     0.0     39.01545    32.412727    40.604443   
DstRate         0.0     0.0     3.401347     4.001571     3.600394   
State           ECO     ECO          CON          CON          CON   
SrcWin          NaN     NaN          NaN          NaN          NaN   
DstWin          NaN     NaN          NaN          NaN          NaN   
sVid            NaN     NaN          NaN          NaN          NaN   
dVid            NaN     NaN          NaN          NaN          NaN   
SrcTCPBase      NaN     NaN          NaN          NaN          NaN   
DstTCPBase      NaN     NaN          NaN          NaN          NaN   
TcpRtt          0.0     0.0          0.0          0.0          0.0   
SynAck          0.0     0.0          0.0          0.0          0.0   
AckDat          0.0     0.0          0.0          0.0          0.0   
Label        Benign  Benign       Benign       Benign       Benign   
Attack Type  Benign  Benign       Benign       Benign       Benign   
Attack Tool  Benign  Benign       Benign       Benign       Benign   

                 5            6            7       8            9        ...  \
Unnamed: 0             5            6            7       8            9  ...   
Seq                    6            7            8       9           10  ...   
Dur             4.997818     0.089686     0.059931     0.0   

## DATA CLEANING

In [4]:
# My domain knowledge about security terms are limited. 
# Therefore I benefited from partial solution about
# data cleaning and filling null values in the website.
# but I did not followed the exact solution.
# _____________________________________________
# Processing of Features that have null values
# ____________________________________________
# sTos has 214 null values     ---- dropped
# dTos has 943067 null values  ---- dropped
# sDSb has 214 null values     ---- dropped
# dDSb has 943067 null values  ---- dropped
# sTtl has 214 null values     ---- fillna(0.0)
# dTtl has 943067 null values  ---- fillna(0.0)
# sHops has 214 null values    ---- fillna(99)
# dHops has 943067 null values ---- fillna(99)
# SrcGap has 937219 null values ---- dropped
# DstGap has 937219 null values ---- dropped
# SrcWin has 973470 null values ---- fillna(median)
# DstWin has 1038812 null values --- fillna(median)
# sVid has 1101319 null values  ---- fillna(99)
# dVid has 1213881 null values  ---- fillna(99)
# SrcTCPBase has 937219 null values ---- fillna(median)
# DstTCPBase has 985843 null values ---- fillna(median)

In [5]:
df.isnull().sum()

Unnamed: 0           0
Seq                  0
Dur                  0
RunTime              0
Mean                 0
Sum                  0
Min                  0
Max                  0
Proto                0
sTos               214
dTos            943067
sDSb               214
dDSb            943067
sTtl               214
dTtl            943067
sHops              214
dHops           943067
Cause                0
TotPkts              0
SrcPkts              0
DstPkts              0
TotBytes             0
SrcBytes             0
DstBytes             0
Offset               0
sMeanPktSz           0
dMeanPktSz           0
Load                 0
SrcLoad              0
DstLoad              0
Loss                 0
SrcLoss              0
DstLoss              0
pLoss                0
SrcGap          937219
DstGap          937219
Rate                 0
SrcRate              0
DstRate              0
State                0
SrcWin          973470
DstWin         1038812
sVid           1101319
dVid       

In [6]:
df['sTos'].value_counts()

sTos
0.0      1209216
186.0       3538
40.0         789
192.0        640
224.0        528
136.0        515
208.0        144
48.0         137
128.0         93
16.0          74
157.0          1
216.0          1
Name: count, dtype: int64

In [7]:
df['sTos'].fillna(0, inplace=True)

In [8]:
df['dTos'].value_counts()

dTos
0.0      267523
186.0      2914
40.0       1413
184.0       550
48.0        390
32.0         32
128.0         1
Name: count, dtype: int64

In [9]:
df.drop(['dTos'], axis=1, inplace=True)

In [10]:
df['sDSb'].value_counts()

sDSb
cs0     1209216
ef         3538
af11        789
cs6         640
cs7         528
af41        515
52          144
af12        137
cs4          93
4            74
39            1
54            1
Name: count, dtype: int64

In [11]:
df['sDSb'].fillna('cs0', inplace = True)

In [12]:
df.drop(['dDSb'], axis=1, inplace = True)

In [13]:
df['sTtl'].value_counts()

sTtl
63.0     981042
249.0    111726
64.0      34553
58.0      29164
117.0     13722
255.0      5309
52.0       2068
53.0       2065
47.0       1747
45.0       1641
37.0       1622
36.0       1610
38.0       1607
51.0       1605
39.0       1603
48.0       1598
56.0       1596
40.0       1585
49.0       1578
55.0       1562
46.0       1560
50.0       1560
42.0       1547
54.0       1542
44.0       1540
43.0       1536
252.0      1529
57.0       1523
41.0       1503
250.0      1317
116.0       608
62.0        461
115.0       356
114.0        65
128.0        26
Name: count, dtype: int64

In [14]:
df['sTtl'].fillna(63, inplace = True)

In [15]:
df['dTtl'].value_counts()

dTtl
59.0     223429
64.0      20061
117.0     11527
53.0       4555
52.0       3363
255.0      2851
62.0       2223
63.0       1547
250.0      1413
116.0       772
252.0       596
115.0       135
51.0         91
54.0         58
47.0         44
48.0         29
50.0         21
43.0         20
41.0         17
114.0        15
42.0         14
46.0          7
44.0          6
37.0          6
49.0          6
45.0          4
236.0         3
95.0          2
211.0         2
78.0          2
228.0         2
230.0         1
233.0         1
Name: count, dtype: int64

In [16]:
df.drop(['dTtl'], axis=1, inplace = True)

In [17]:
df['sHops'].value_counts()

sHops
1.0     986351
7.0     113249
0.0      34579
6.0      30481
11.0     15787
12.0      2676
13.0      1961
17.0      1747
19.0      1641
14.0      1625
27.0      1622
28.0      1610
26.0      1607
25.0      1603
16.0      1598
8.0       1596
24.0      1585
15.0      1578
9.0       1562
18.0      1560
22.0      1547
10.0      1542
20.0      1540
21.0      1536
4.0       1529
23.0      1503
2.0        461
Name: count, dtype: int64

In [18]:
df['sHops'].fillna(1, inplace = True)

In [19]:
df['dHops'].value_counts()

dHops
5.0     223429
0.0      20061
11.0     16082
1.0       4398
12.0      4135
2.0       2223
6.0       1413
4.0        596
13.0       226
10.0        58
17.0        44
14.0        36
16.0        29
21.0        20
23.0        18
22.0        14
20.0         9
18.0         7
15.0         6
27.0         6
19.0         4
33.0         2
45.0         2
50.0         2
28.0         2
26.0         1
Name: count, dtype: int64

In [20]:
df['dHops'].fillna(5, inplace = True)

In [21]:
df.drop(['SrcGap'], axis =1, inplace = True)

In [22]:
df.drop(['DstGap'], axis = 1, inplace = True)

In [23]:
df['SrcWin'].fillna(df['SrcWin'].median(), inplace=True)

In [24]:
df['DstWin'].fillna(df['DstWin'].median(), inplace=True)

In [25]:
df['sVid'].fillna(99, inplace = True)

In [26]:
df['dVid'].fillna(99, inplace = True)

In [27]:
df['SrcTCPBase'].value_counts()

SrcTCPBase
4.693370e+08    1000
2.715121e+09    1000
8.676379e+08    1000
1.668789e+09    1000
1.736983e+07    1000
                ... 
2.282491e+09       1
4.057869e+09       1
6.152591e+08       1
2.813210e+09       1
2.237373e+09       1
Name: count, Length: 203756, dtype: int64

In [28]:
df['SrcTCPBase'].fillna(df['SrcTCPBase'].median(), inplace= True)

In [29]:
df['DstTCPBase'].fillna(df['DstTCPBase'].median(), inplace= True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215890 entries, 0 to 1215889
Data columns (total 47 columns):
 #   Column       Non-Null Count    Dtype  
---  ------       --------------    -----  
 0   Unnamed: 0   1215890 non-null  int64  
 1   Seq          1215890 non-null  int64  
 2   Dur          1215890 non-null  float64
 3   RunTime      1215890 non-null  float64
 4   Mean         1215890 non-null  float64
 5   Sum          1215890 non-null  float64
 6   Min          1215890 non-null  float64
 7   Max          1215890 non-null  float64
 8   Proto        1215890 non-null  object 
 9   sTos         1215890 non-null  float64
 10  sDSb         1215890 non-null  object 
 11  sTtl         1215890 non-null  float64
 12  sHops        1215890 non-null  float64
 13  dHops        1215890 non-null  float64
 14  Cause        1215890 non-null  object 
 15  TotPkts      1215890 non-null  int64  
 16  SrcPkts      1215890 non-null  int64  
 17  DstPkts      1215890 non-null  int64  
 18  To

In [31]:
df['Attack Type'].replace(['Benign', 'UDPFlood', 'HTTPFlood', 'SlowrateDoS',
                            'TCPConnectScan', 'SYNScan', 'UDPScan', 'SYNFlood', 'ICMPFlood'], 
                          [0, 1, 2, 3, 4, 5, 6, 7, 8], inplace=True)

In [32]:
#df_ = df.sample(1000000)

In [33]:
y = df['Attack Type']

In [34]:
x = df.drop('Attack Type', axis=1)

In [35]:
x = df.drop(['Attack Tool', 'Label'], axis = 1)

In [36]:
x = pd.get_dummies(x, drop_first = True)


In [37]:
def algo_test(x,y):
#def algo_test(x_train,x_test,y_train,y_test):
    
    import numpy as np

    from scipy import stats
    import matplotlib.pyplot as plt
    %matplotlib inline 
    import seaborn as sns


    from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
    from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
    from sklearn.tree import ExtraTreeClassifier
    from sklearn.ensemble import GradientBoostingRegressor
    from xgboost import XGBRegressor 

    from sklearn.model_selection import train_test_split

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.ensemble import ExtraTreesClassifier
    from xgboost import XGBClassifier

    import warnings
    warnings.filterwarnings('ignore')
#plt.style.use('')

    
    
    G = GaussianNB()
    B = BernoulliNB()
    #K = KNeighborsClassifier()
    L = LogisticRegression()
    D = DecisionTreeClassifier()
    RF = RandomForestClassifier()
    ETC = ExtraTreesClassifier()
    XG = XGBClassifier()

    
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 13)
    
    algos = [G,B,L,D, RF, ETC, XG]
    #algos = [G,B,L,D,  RF, ETC]
    
    #algo_names = [ "Gaussian", "Bernoulli", "K-Neighbors", "Logistic Regression", "Decision Tree", "Random Forest", "ExtraTreeClassifier" ]
    algo_names = [ "Gaussian", "Bernoulli","Logistic Regression", "Decision Tree", \
                  "Random Forest", "ExtraTreeClassifier","XGBClassifier" ]
    
    ASC = [];
    
    result =  result = pd.DataFrame(columns =['Accuracy_Score'], index = algo_names)
    
    i = 0;
    for algo in algos :
        
        algo.fit(x_train,y_train)
        #print (accuracy_score(  y_test, algo.predict(x_test) ))
        ASC.append(  accuracy_score(  y_test, algo.predict(x_test) ) )
        
        print( "Confusion matrix: ",format(algo_names[i]) )
        i = i+1;
        print ( confusion_matrix(algo.predict(x_test),y_test) )
        #print (classification_report(y_test,algo.predict(x_test) ))
        
        #algo.fit(x,y)
        #print (accuracy_score(  y, algo.predict(x) ))
        #ASC.append(  accuracy_score(  y, algo.predict(x) ) )
    
    
    result.Accuracy_Score = ASC;

    return result.sort_values('Accuracy_Score', ascending=False)

In [38]:
algo_test(x,y)

Confusion matrix:  Gaussian
[[ 4988     0   329     0     0     0     0     0     0]
 [85515 89991     0     0     2   266   866     0     0]
 [  178     0  5421     5     0     0     0     0     0]
 [ 1176     0  8559   531     0     0     0     0     0]
 [   77     0     0     1   400     0     1     0     0]
 [   16     0     0     0  3305  3257     3     0     0]
 [    3     0     0     0   357   539     4     0     0]
 [  666     0 14232 13979     0     4     0  1954     0]
 [ 2551  1453     0     0     4     2  2324     0   219]]
Confusion matrix:  Bernoulli
[[93087     0     1    34     1     1     0     0     0]
 [    0 81202     0     0     0     0     0     0     0]
 [   94     0 17064  1299     0     0     0     0     0]
 [  982     0 11476 13174    13     0     0     0     0]
 [    0     0     0     0   603   444     1    90     0]
 [    1     0     0     0  3417  3603     0   194     0]
 [    0 10242     0     0     2     2  3188     0     0]
 [   23     0     0     9    2

Accuracy_Score
Decision Tree              1.000000
XGBClassifier              1.000000
Random Forest              0.999996
ExtraTreeClassifier        0.999988
Bernoulli                  0.879232
Logistic Regression        0.481540
Gaussian                   0.439041